<?php
	$cus= $this->cus;
?>
<div class="list list-add">
	<form name="frmAddAdm" method="post" enctype="multipart/form-data">
		<div class="action">
			<h2 class="title">Create Customer</h2>
			<div class="save-reset">
				<input class="button" type="submit" value="SAVE" />&nbsp;&nbsp;
				<input class="button" type="reset" value="Reset" />
			</div>
		</div>
		<div class="clr"></div>
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td>Customer Name</td>
				<td><input type="text" name="cus_name" value="<?php echo $cus['cus_name']; ?>" />
					<?php if($this->errcn): ?>
					<label class="err"><?php echo $this->errcn ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr>
				<td>Customer Email</td>
				<td><input type="text" name="cus_email" value="" />
					<?php if($this->errcm): ?>
					<label class="err"><?php echo $this->errcm ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr>
				<td>Customer Phone</td>
				<td><input type="text" name="cus_phone" value="<?php //echo $cat['cat_name']; ?>" />
					<?php if($this->errcp): ?>
					<label class="err"><?php echo $this->errcp ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr>
				<td>Customer Address </td>
				<td><input type="text" name="cus_add" value="<?php //echo $cat['cat_name']; ?>" />
					<?php if($this->errcadd): ?>
					<label class="err"><?php echo $this->errcadd ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr>
				<td valign="top">Avatar</td>
				<td><input type="file" id="" name="avatar" cols="30" rows="5" ><?php //echo $cat['cat_des']; ?></input>
				<?php if($this->errcava): ?>
					<label class="err"><?php echo $this->errcava ?></label>
					<?php endif; ?>
				</td>
			</tr>
		</table>
	</form>
</div>