
<?php echo $this->doctype(); ?>

<html xmlns = "http://www.w3.org/1999/xhtml"> 
<head>
	<?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8'); ?> 
    <?php echo $this->headTitle('Login zfe4c'); ?> 
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/app/templates/admin/css/style.css'); ?>
</head>
<body>
	<?php echo $this->layout()->content; ?>
</body>
</html>   