<?php 
	$errsc       = $this->errsc;
	$errpname    = $this->errpname;
	$errprice    = $this->errprice;
	$errquantity = $this->errquantity;
	$errcolor    = $this->errcolor;
	$errsize     = $this->errsize;
	$errimg      = $this->errimg;
	$errdes      = $this->errdes;
	$cats      = $this->cat;
	$product     = $this->product;
	$colors      = $this->color;
	$sizes       = $this->size;
?>
<script>
	function addImgGal(){
		$('#imggal').append('<input type="file" name="imggal[]"/><br/>');
		$("input[name='imggalflag']").val('1');
	}
	function getSubCat(id){
		if(id==-1){
			alert('you must choose category');
			return false;
		}else{
			
			
			$.ajax({
        				type: 'POST',
        				url	: '<?php echo $this->baseUrl() ?>/admin/product/getsubcat/id/'+id,
        				dataType: 'html',
        				
        				success: function(msg){
        					$("#subcat").html(msg);
							return false;
        				}		
        				
        			});
		}
	}
</script>
<div class="list-add">
	<form name="frmAddPro" method="post" enctype="multipart/form-data">
		<div class="action">
			<h2 class="title">Add Product</h2>
			<div class="save-reset">
				<input class="button" type="submit" value="SAVE" />&nbsp;&nbsp;
				<input class="button" type="reset" value="Reset" />
			</div>
		</div>
		<div class="clr"></div>
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td>Category: </td>
				<td>
					<select name="catname" onchange="getSubCat(this.value)">
						<option value="-1"><?php echo 'choose category'?></option>
						<?php foreach($cats as $cat): ?>
						<option value="<?php echo $cat['cat_id'] ?>"><?php echo $cat['cat_name']; ?></option>
						<?php endforeach; ?>
					</select>
					<?php if($errsc): ?>
					<label class="err"><?php echo $errsc; ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr id="subcat">

			</tr>
			<tr>
				<td>Product name: </td>
				<td>
					<input type="text" name="proname" value="<?php echo $product['pro_name']; ?>" />
					<?php if($errpname): ?>
					<label class="err"><?php echo $errpname; ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr>
				<td>Product price: </td>
				<td>
					<input type="text" name="proprice" value="<?php echo $product['pro_price']; ?>" />
					<?php if($errprice): ?>
					<label class="err"><?php echo $errprice; ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr>
				<td>Product image: </td>
				<td>
					<input type="file" name="proimg" value="browser" />
					<input type="button" onclick="addImgGal()" value="them anh" />
					<input type="hidden" name="imggalflag" value="0"/>
					<div id="imggal" class=""></div>
					<?php if($errimg): ?>
					<label class="err"><?php echo $errimg; ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr>
				<td>Product quantity: </td>
				<td>
					<input type="text" name="proquantity" value="<?php echo $product['pro_quantity']; ?>" />
					<?php if($errquantity): ?>
					<label class="err"><?php echo $errquantity; ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr>
				<td>Product color: </td>
				<td>
					<select name="procolor">
						<option value="-1">Choose color</option>
						<?php foreach($colors as $color): ?>
						<option value="<?php echo $color['col_id'] ?>"><?php echo $color['col_name'] ?></option>
						<?php endforeach; ?>
					</select>
					<?php if($errcolor): ?>
					<label class="err"><?php echo $errcolor; ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr>
				<td>Product size: </td>
				<td>
					<select name="prosize">
						<option value="-1">Choose size</option>
						<?php foreach($sizes as $size): ?>
						<option value="<?php echo $size['siz_id']; ?>"><?php echo $size['siz_name']; ?></option>
						<?php  endforeach; ?>
					</select>
					<?php if($errsize): ?>
					<label class="err"><?php echo $errsize; ?></label>
					<?php endif; ?>
				</td>
			</tr>
			<tr>
				<td valign="top">Description: </td>
				<td>
					<textarea id="txtSortDes" name="prodes" cols="60" rows="10" ><?php echo $product['pro_des']; ?></textarea>
					<?php if($errdes): ?>
					<label class="err"><?php echo $errdes; ?></label>
					<?php endif; ?>
				</td>
			</tr>
		</table>
	</form>
</div>