<div class="menu-left">
	<ul class="left-menu">
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/manager/">Admin</a></li>
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/category/">Category</a></li>
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/component/">Component</a></li>
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/post/">Post</a></li>
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/file/">File</a></li>
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/member/">Member</a></li>
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/customer/">Customer</a></li>
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/comment/">Comment</a></li>
		<li><a href="<?php echo $this->baseUrl(); ?>/admin/logout/">Logout</a></li>
	</ul>
</div>